### ISSUE TITLE
Support for discrete parameter spaces

### ISSUE THREAD

**Issue by adomasbaliuka** [michaelhush/M-LOOP#119]
**Is your feature request related to a problem? Please describe.**
I'm trying to use your software for some optimizations of experimental parameters. One potential problem is that some of my parameters have discrete values, e.g., integers 0, 1, ..., 255, in addition to other parameters that may be continuous. I don't know how to treat these parameters within your framework.

**Describe the solution you'd like**
- Could you upport for discrete parameter ranges?
- when and how can one treat discrete ranges as continuous by rounding? How well could this work?

**Describe alternatives you've considered**
I'm not so familiar with the mathematical background for your optimization methods. Thus, I'm not sure to what extent discrete parameter ranges are compatible with Gaussian processes or the other algorithms employed. However, the library scikit-optimize (https://pypi.org/project/scikit-optimize/) also uses Gaussian process regression and does allows discrete or categorical parameter ranges. As scikit-learn is commonly used for hyperparameter optimization in machine learning (many dimensions of discrete values), I assume that there are practical ways to allow discrete values in Gaussian process regression.

I have been using scikit-optimize. However, your library seems to have some features that scikit-optimize is lacking, such as parallel data acquisition and processing. Therefore I will be trying it as well and comparing results.

An obvious "alternative" is to treat the discrete spaces as continuous and round off the parameters when they are fed to experimental control. For reasonably fine-grained parameter ranges, such as 256 or 1000 distinct values, I imagine this might work, even though it technically violates some smoothness assumptions implied by the algorithms? I would love to hear some comments from you if this is feasible or would break the optimization. What kinds of hyper-parameters or modes of operation would be best suited to this scenario?

**Comment by zakv** [comment]
Hi adomasbaliuka,

My comments below are about M-LOOP optimizations which use a Gaussian process or Neural net learner, which are the more interesting/unique optimization methods in the package. The behavior for differential evolution and Nelder-Mead (more standard optimization approaches which are also supported by M-LOOP) will likely be different.

I would suspect that for reasonable functions, optimizing over 256 values would work fine just by truncating. Generally I would say that M-LOOP would probably work ok when the discrete steps correspond to some numeric parameter where the cost varies somewhat slowly (i.e. adjacent discrete values give reasonably similar costs) as the input parameter is changed. For example, I suspect M-LOOP would be reasonably good at minimizing the function `(x - 128)**2` where `x` is truncated to be an 8 bit integer.

M-LOOP probably wouldn't be good at discrete variables where the cost between adjacent points isn't well correlated. For example, if you wanted to optimize a function `f(x)` with 8-bit `x` which has a completely random value for each possible value of `x`, then it wouldn't work so well. Similarly, if you had some function that took "apple", "banana", "orange", etc. as an input and gave a different cost for each, then M-LOOP probably wouldn't handle that well. If you have just a few possibilities for the discrete value though, then you could do one M-LOOP optimization over all the continuous variables for each value of the discrete variable. Then you could compare the results to find the optimal discrete value. Basically you could do a grid search over the discrete variable(s), performing one optimization at each grid point.

All that said, my recommendation would be to just try different things out. Try the different optimization algorithms supported by M-LOOP and see what works. It could be that one or more work great for your particular problem, or it could be that none work at all for your particular problem. If you haven't already, I would also suggest reading up a bit on Bayesian optimization as that may help you understand your results. The main thing to know is that a machine learning model is trained based on results from some initial function evaluations, then that machine learning model is used to predict good parameters. Those parameters are then tested and the machine learning model is updated with the results, at which point the updated model is used to predict good parameters.

I should also mention that M-LOOP is mainly targeted at optimizing functions that are costly to evaluate and may have noise in the results. If you can evaluate the function quickly, other optimization algorithms will likely be faster as they don't require training a machine learning model on the data.

Cheers,
Zak

**Comment by zakv** [comment]
This thread has been idle for a bit over a year now, so I'll go ahead and close it. Feel free to open it again if there is more to discuss
