### ISSUE TITLE
Default ANN - Possible to create custom ANN

### ISSUE THREAD

**Issue by ScotchWhiskey** [michaelhush/M-LOOP#156]
Hi,

Apologies as this is not really an issue but an asking for advice. I am currently using M-LOOP for optimising ring resonators on a silicon chip. I would like to employ an ANN to do this alongside online optimisation, having already been using the GPR in M-LOOP. I am aware the Neural Net controller can be used out of the box so to speak, however I am unsure as to how to find the depth of this ANN, it's activation functions etc. I am wondering how one can create their own ANN to be used in M-LOOP? So for example can one be created in keras and then imported into M-LOOP, or created in M-LOOP itself. I have read the paper 'Applying machine learning optimization methods to the production of a quantum gas' were they have a self defined ANN and use it in M-LOOP, but I do not know how to do this myself.

Thankyou for any help!

**Comment by zakv** [comment]
Hi ScotchWhiskey,

As for the built-in neural net hyperparamters, they are set [here](https://github.com/michaelhush/M-LOOP/blob/2d9e6a5a73438c3ff74c334a8fe4e67e7ab4e3df/mloop/neuralnet.py#L503) (see [here](https://github.com/michaelhush/M-LOOP/blob/2d9e6a5a73438c3ff74c334a8fe4e67e7ab4e3df/mloop/neuralnet.py#L43) for what those argument values correspond to). The nets have an input layer with one node for each optimization parameter, followed by five hidden layers with 64 nodes each, then an output layer with a single node. Each layer is fully-connected and uses a GELU activation function as defined [here](https://github.com/michaelhush/M-LOOP/blob/2d9e6a5a73438c3ff74c334a8fe4e67e7ab4e3df/mloop/neuralnet.py#L501).

As for providing your own neural net, I think the easiest way to get started with that might just be to set up an editable installation of M-LOOP by cloning the git repo to your computer and installing it into your Python environment with `pip -e`. Then you can edit your local copy of M-LOOP however you'd like, changing the neural net topology, activation function, and so on. This approach is a bit hacky but would probably take the least amount of setup.

A less-hacky way to use your own neural net would be to write your own optimizer classes. As [briefly mentioned in the docs](https://m-loop.readthedocs.io/en/v3.3.1/examples.html#controllers), M-LOOP supports using third-party optimizer classes. However, the process for writing them is somewhat complicated and isn't documented, so I wouldn't recommend doing so until you've at least done some proof of principle demonstrations with the simpler/hacky approach to show that it would actually be worth the effort to implement it properly.

Alternatively, I believe that the package BoTorch (another Bayesian optimization package) allows more flexibility for defining the machine learning model, though I've never used it myself.

Just to check though, have you tried simply using M-LOOP's built-in neural net optimizer? You may just find that it works well out-of-the-box.

Cheers,
Zak

**Comment by ScotchWhiskey** [comment]
Hi,

Thankyou for the prompt response. I will indeed use the provided NN. I was just not sure the depth of it, number of nodes etc. However it seems like it should work for the problem at hand. 

Thankyou again.

SW

**Comment by zakv** [comment]
Sounds good! I'll go ahead and close this issue then
