### ISSUE TITLE
Incompatible with latest numpy

### ISSUE THREAD

**Issue by Patschke** [michaelhush/M-LOOP#157]
**Bug Desctiption**
Since version 1.24 `numpy` no longer has the attributes `np.float` (or `np.int` etc). They have been deprecated since numpy 1.20. They are still used in M-LOOP, which will cause issues when using latest numpy. See https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated for the deprecation note. 

**To Reproduce**

1. Install numpy 1.24
2. Try to use learners.py
3. `AttributeError: module 'numpy' has no attribute 'float'.`

**Expected behavior**
Don't use stuff that doesn't exist. 

**Additional context**
This is trivial to fix (just replace `np.float` with `float`). I can create a PR if that helps.

**Comment by zakv** [comment]
Thanks for the bug report. This is an easy fix so I can probably knock it out today
