### ISSUE TITLE
A typo in controllers.py

### ISSUE THREAD

**Issue by yufei11xyz** [michaelhush/M-LOOP#175]
Hi there,
Thanks for your work.

In controllers.py, I find a typo on line 475 of controllers.py, which should be self.max_boundary.
![image](https://github.com/michaelhush/M-LOOP/assets/160806909/d58e91fc-d0a1-4e55-9c66-e08ade336a2f)

**Comment by yufei11xyz** [comment]
In addition, in learners.py:

Line 576, I think a shallow copy "self.init_simplex_corner=copy.copy(self.min_boundary)" is expected. In this case, the update of self.init_simplex_corner in Line 578 will not affect "self.min_boundary". Otherwise, when simply using "self.init_simplex_corner=self.min_boundary", the value of min_boundary is changed with the update of "self.init_simplex_corner".
![image](https://github.com/michaelhush/M-LOOP/assets/160806909/a79e46eb-5870-4404-b196-7a7aa9dc48ae)

**Comment by zakv** [comment]
Good catches! These have now been fixed by #176 and #177. Thanks for the helpful and detailed bug report!
