### ISSUE TITLE
Error when reproducing visualizations

### ISSUE THREAD

**Issue by AndBM** [michaelhush/M-LOOP#23]
I am trying to reproduce some visualizations as you have written in [http://m-loop.readthedocs.io/en/latest/visualizations.html#reproducing-visualizations](url), but when I run the sample code with one of my archives, I get the following error:

>/path/anaconda3/lib/python3.5/site-packages/sklearn/gaussian_process/gpr.py:308: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "
Traceback (most recent call last):
  File "revisualize.py", line 6, in <module>
    mlv.create_gaussian_process_learner_visualizations('M-LOOP_archives/learner_archive_2017-02-13_10-07.txt',file_type='txt')
  File "/path/M-LOOP/mloop/visualizations.py", line 360, in create_gaussian_process_learner_visualizations
    visualization.plot_all_minima_vs_cost()
  File "/path/M-LOOP/mloop/visualizations.py", line 489, in plot_all_minima_vs_cost
    if not self.has_all_minima:
AttributeError: 'GaussianProcessVisualizer' object has no attribute 'has_all_minima'

This is both for processes that have finished and have been interrupted. How do I fix this? Archives below.

[controller_archive_2017-02-13_10-07.txt](https://github.com/michaelhush/M-LOOP/files/850492/controller_archive_2017-02-13_10-07.txt)
[learner_archive_2017-02-13_10-07.txt](https://github.com/michaelhush/M-LOOP/files/850493/learner_archive_2017-02-13_10-07.txt)

**Comment by michaelhush** [comment]
I'll look into this tomorrow. This might be a bug in M-LOOP where the boolean has_all_minima has not been defined.

**Comment by michaelhush** [comment]
There was an bug with the one of the plots which attempts to plot the location of all the local minima. I'm going to update M-LOOP with a fix for the bug, and also change the default not to produce that plot (it takes a lot of time to calculate). So try the updated version.

If you want to fix the problem without updating, you can just stop M-LOOP from plotting the figure creating the problem using:

`import mloop.visualizations as mlv`
`import matplotlib.pyplot as plt`
`mlv.configure_plots()`
`mlv.create_contoller_visualizations('controller_archive_2017-02-13_10-07.txt',file_type='txt')`
`mlv.create_gaussian_process_learner_visualizations('learner_archive_2017-02-13_10-07.txt',file_type='txt',plot_all_minima_vs_cost=False)`
`plt.show()`
