### ISSUE TITLE
M-LOOP reading the same cost twice

### ISSUE THREAD

**Issue by AndBM** [michaelhush/M-LOOP#31]
The following problem has turned up recently in my work with M-LOOP, and I haven't been able to understand why:

I'm using the file interface with another program, let's call it `TARGET`. In my interface I have added some terminal output to print when `TARGET` starts and stops. I have begun experiencing the following sequence in the terminal:

    INFO Run: 1
    INFO params [<paramset1>]
    Running TARGET...
    TARGET done.
    INFO cost <cost1>
    INFO Run: 2
    INFO params [<paramset2>]
    Running TARGET...
    INFO cost <cost1>
    INFO Run: 3
    INFO params [<paramset3>]
    TARGET done.
    INFO cost <cost2>

The problem here is that M-LOOP for some reason reads the same cost twice. This means it will assign the wrong cost to a set of parameters twice, first when it copies the previous cost, and second when the next cost is applied to a set of new, wrong parameters. Note that nothing happens in the interface between `TARGET` runs and `TARGET` stops, it simply waits for `TARGET` to finish.

I have checked to see if `exp_output.txt` for some reason might not be deleted, causing M-LOOP to think the experiment finished again, but this is not the case. It is deleted at the correct point in the program. I have the latest version of M-LOOP. This seems a serious problem to me, as the program will completely misunderstand the parameter-cost space in this way. But for some reason it has only recently begun being a problem, and it only happens sometimes.

Can you help me fix this?

**Comment by michaelhush** [comment]
Can you attach the log file and archives you have from a run that went wrong?

I'll try and reproduce the error.

**Comment by AndBM** [comment]
Here is a short log where the problem happened immediately, and I then shut down using keyboard interrupt.

[M-LOOP_2017-08-02_10-47.txt](https://github.com/michaelhush/M-LOOP/files/1193363/M-LOOP_2017-08-02_10-47.txt)

I've been using keyboard interrupt to stop the optimization a number of times, and instructed my interface to terminate the MLOOP process. I must admit, however, that I am not very experienced in handling processes and subprocesses, so is this a mistake? The problem could exist if I somehow had to instances of MLOOP running, but I can't see any MLOOP process when using `top`, and stuff like the log is only written once.

**Comment by AndBM** [comment]
Hi Michael

Do you have any ideas for a solution?

**Comment by charmasaur** [comment]
I had a look at this but nothing jumped out. A few questions that might help narrow it down:
 - what operating system are you using?
 - how did you install M-LOOP (from source at head, or through pip)?
 - when it goes wrong, is it always the first cost that's read twice? And after that does it read the costs in order (so it reads cost 1, cost 1, cost 2, cost 3, cost 4, ...)? Or does it sometimes read other costs twice too?

**Comment by michaelhush** [comment]
I realised the other day that there were a bunch of errors in the main branch that had been corrected in the NeuralNet branch. So I've finally got around to merging them together.

@AndBM This might fix your problem. Try updating M-LOOP from the repository it should have a new version number. I'll also update the pip distribution.

**Comment by AndBM** [comment]
@charmasaur Currently I am using Ubuntu 16.04. M-LOOP is installed recently with git. It doesn't seem to be systematic which costs are read twice. The only system I can see currently is that I don't think it makes any mistakes until at least one "bad" result has been reported, but I get a lot of "bad" results, so it's hard to be sure.
@michaelhush I updated, but it didn't help.

I've done some more debugging, and it seems there is a problem with the existence of the exp_output.txt file. The program I have interfaced with M-LOOP runs at least 1 minute, but when this problem occurs, M-LOOP comes with different guesses within a few seconds. The last 6 guesses in this log

[M-LOOP_2017-10-11_22-54.log](https://github.com/michaelhush/M-LOOP/files/1379139/M-LOOP_2017-10-11_22-54.log)

are in 3 sets of 2 guesses with 2-4 seconds between. I made a program to monitor the existence of exp_output.txt, and these 3 sets correlate with exp_output.txt being deleted and suddenly reappearing. By noting when my interface produces an exp_output.txt (see below), I have seen that this sudden reappearance is not caused by my interface writing an extra exp_output.txt. Can I be doing something that disturbs M-LOOPs deletion of exp_output.txt? Or can there be some system bug in the deletion that causes exp_output to reappear?

For reference, here are my writing functions (python 3):
```python
def write_bad(path):
	t = datetime.now().strftime("%H:%M:%S")
	print("DEBUG  Writing output at time ", t)

	with open(path, 'w') as file:
		file.write('bad = True\n')

def write_cost(cost,path):
	t = datetime.now().strftime("%H:%M:%S")
	print("DEBUG  Writing output at time ", t)

	with open(path, 'w') as file:
		file.write('cost = %f\n' % cost)
```

Note: Other people using a basic version of my interface and M-LOOP (but for a different problem) seemingly don't have this issue.

**Comment by AndBM** [comment]
It seems Dropbox on Ubuntu was bringing back exp_output when it was deleted, interrupting the file interface. I have moved out of Dropbox and everything is fine again. Thank you for helping me!

**Comment by michaelhush** [comment]
That's still strange. I run most of my code out of Dropbox and I haven't had this trouble. I'll make a comment in the documentation about this somewhere.

**Comment by brycehenson** [comment]
Hi,
We have had issues with running in dropbox, the solution is to use "pause
syncing" on dropbox

------------------------------

Bryce Henson

M:0415083684

O:0261255406

Ph.D. student, He* BEC Group

Laser Physics Centre

Research School of Physics and Engineering

Australian National University

http://physics.anu.edu.au/people/profile.php?ID=1663

------------------------------
