### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by nfrik** [michaelhush/M-LOOP#33]
I am following your installation instructions on Ubuntu 16.04. I have python 3.5.2 and fully functional tensorflow-gpu 1.2.0 installed on it, but I receive the following error:

```
Processing dependencies for M-LOOP==2.2.0
Searching for tensorflow>=1.2.0
Reading https://pypi.python.org/simple/tensorflow/
No local packages or working download links found for tensorflow>=1.2.0
error: Could not find suitable distribution for Requirement.parse('tensorflow>=1.2.0')
```

**Comment by michaelhush** [comment]
It's possible that tensor-flow has been installed in a different version of python than the one you are installing M-LOOP for. 

A few questions:
1. Did you use anaconda to install python?
2. When you run python in the same terminal you are using to install M-LOOP, does it say it is the anaconda version?
3. When you're in the anaconda installation of python does "import tensorflow as tf", then say "print(tf.__version__)" work?

On my end I'll do a fresh install on my ubuntu and double check that it is able to search the pip repository correctly for tensorflow. It has worked in the past...

**Comment by nfrik** [comment]
Thanks for quick response. Everything worked once I installed the most recent CPU version of tensorflow through pip in a local virtual environment. But it still refuses locate GPU version of tensorflow 1.2.0 installed from wheel.
