### ISSUE TITLE
NeuralNetVisualizer calls nonexistent function safe_squeeze()

### ISSUE THREAD

**Issue by zakv** [michaelhush/M-LOOP#38]
Hi all,

I came across this issue when trying to plot the results from an optimization run done using the neural_net controller. Here is the code to produce the error:

```python
import mloop.visualizations as mlv

filename = r"C:\path\to\learner_archive_2020-02-22_06-44.txt"
file_type='txt'

visualization = mlv.NeuralNetVisualizer(filename, file_type)
```

and here's the resulting traceback:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-1-21542a9fb6a5> in <module>
     12 # mlv.configure_plots()
     13 # mlv.create_neural_net_learner_visualizations(learner_archive,file_type='txt')
---> 14 visualization = mlv.NeuralNetVisualizer(filename, file_type)
     15 
     16 plt.show()

~\.conda\envs\labscript\lib\site-packages\mloop\visualizations.py in __init__(self, filename, file_type, **kwargs)
    608                                                   nn_training_file_type = file_type,
    609                                                   update_hyperparameters = False,
--> 610                                                   **kwargs)
    611 
    612         import plotly.plotly as py

~\.conda\envs\labscript\lib\site-packages\mloop\learners.py in __init__(self, trust_region, default_bad_cost, default_bad_uncertainty, nn_training_filename, nn_training_file_type, minimum_uncertainty, predict_global_minima_at_end, **kwargs)
   1478             #Data from previous experiment
   1479             self.all_params = np.array(self.training_dict['all_params'], dtype=float)
-> 1480             self.all_costs = mlu.safe_squeeze(self.training_dict['all_costs'])
   1481             self.all_uncers = mlu.safe_squeeze(self.training_dict['all_uncers'])
   1482 

AttributeError: module 'mloop.utilities' has no attribute 'safe_squeeze'
```

Maybe this function was superseded by `safe_cast_to_array()`?

I'm happy to submit the learner archive if desired. I'd also be happy to fix the bug and issue a pull request if it's a simple matter of changing `safe_squeeze()` to `safe_cast_to_array()`.

Cheers,
Zak

**Comment by zakv** [comment]
I dug through the git history a bit and it looks like `safe_squeeze()` was added in 97d5b23358bd8bf19ba818588a3e5d279809fc4a and then removed in 9835e3f7ef66762c7c4138d434cf7a1f44e71b65. Then safe_cast_to_array() was added in 3bc037458862118d13703c13271cea3204c7377d. It looks like the only difference is that `safe_squeeze()` gave the option to specify the `dtype` of the returned array, and ensured it was `float` by default. I've copy/pasted the code for each function below for reference.

```python
def safe_cast_to_array(in_array):
    '''
    Attempts to safely cast the input to an array. Takes care of border cases
    
    Args:
        in_array (array or equivalent): The array (or otherwise) to be converted to a list.
    
    Returns:
        array : array that has been squeezed and 0-D cases change to 1-D cases
    
    '''
    
    out_array = np.squeeze(np.array(in_array))
    
    if out_array.shape == ():
        out_array = np.array([out_array[()]]) 
    
    return out_array
```

```python
def safe_squeeze(in_array, set_dtype = float):
    '''
    Attempts to squeeze an array, but has a different behavior for arrays with only a single value. 
    
    Args:
        in_array (array): The array to be squeezed
    
    Returns:
        array: Array.
    '''
    
    out_array = np.squeeze(np.array(in_array, dtype=set_dtype))
    if out_array.shape == ():
        out_array = np.array([out_array[()]])
    
    return out_array
```

Experimentally I've tried monkey patching things to replace the calls to `safe_squeeze()` with calls to `safe_cast_to_array()` and things worked fine. Example code below (file names and types are set elsewhere):

```python
import mloop.visualizations as mlv

# Monkey patch safe_cast_to_array() in place of safe_squeeze() in neural net visualizer code.
mlv.mlu.safe_squeeze = mlv.mlu.safe_cast_to_array

# Make the plots.
mlv.configure_plots()
mlv.create_controller_visualizations(controller_archive, file_type=file_type)
mlv.create_neural_net_learner_visualizations(learner_archive, file_type=file_type)
```

@michaelhush @charmasaur I can go ahead and replace the calls to `safe_squeeze()` with calls to `safe_cast_to_array()` and submit a pull request. Alternatively, I could add the code for `safe_squeeze()` back in to `utilities.py`.

**Comment by charmasaur** [comment]
Thanks for the sleuthing! Migrating `safe_squeeze()` calls to `safe_cast_to_array()` sounds good to me.

(incidentally, the revert commit was when I accidentally merged some development work to master... I guess I must have messed something up, and accidentally also reverted some stuff that was already in master)
