### ISSUE TITLE
Problem in mloop.visualizations.mlv.ControllerVisualizer

### ISSUE THREAD

**Issue by sebbleroni** [michaelhush/M-LOOP#67]
I realized that when using the the function plot_hyperparameters_vs_run I could get an error quite easily in case I had less different length scales than parameters (e.g. when having only one length scale for all). I could easily circumvent this by simply specifying a parameter subset but fixing this might be useful. 

Thank you for the great work you put into this project. I love using M-LOOP!

**Comment by zakv** [comment]
Hi @sebbleroni, I should get a chance to take a look at fixing that within the next few days. If you don't mind doing so, could you share the learner archive from the optimization where you observed this error?

**Comment by zakv** [comment]
Actually I managed to reproduce this bug so don't worry about sharing the archive. I'll issue a PR to resolve it shortly. Thanks for reporting it!

**Comment by sebbleroni** [comment]
> Actually I managed to reproduce this bug so don't worry about sharing the archive. I'll issue a PR to resolve it shortly. Thanks for reporting it!

Hi, sorry for the late reply and thank you for picking up the issue!
