### ISSUE TITLE
Make creating of new figures optional

### ISSUE THREAD

**Issue by sebbleroni** [michaelhush/M-LOOP#70]
One thing I would find convenient was to be able to aranging the plots created by `mloop.visualizations` more freely (e.g. position the plots in a specific figure/subfigure). For that one could make the lines

`figure_counter += 1`
`plt.figure(figure_counter)`

optional.  I think that would be a useful feature, but obviously not necessary.

**Comment by zakv** [comment]
Yeah for a while I considered issuing a PR to add more control over where the plots are generated, but I couldn't decide on a simple, flexible, and backwards compatible way to do it nicely.

A quick/hacky way to do something similar to what you've mentioned is to manually change the value of `figure_counter` before calling the plotting method:
```python
# Required imports.
import matplotlib.pyplot as plt
import mloop.visualizations as mlv

# Settings.
controller_archive = r'some_controller_archive.txt'  # Controller archive file name and path.
desired_fig_number = 34  # Some random figure number.

# Make the plot on the desired figure.
controller_visualizer = mlv.ControllerVisualizer(controller_archive)
plt.figure(desired_fig_number)
figure_counter_bak = mlv.figure_counter  # Backup figure counter to restore its value later.
mlv.figure_counter = desired_fig_number - 1
controller_visualizer.plot_cost_vs_run()
mlv.figure_counter = figure_counter_bak
```
I don't think this hack let's you make good use of `plt.sca()` so it's not quite as good as your suggestion in that way. Ideally you'd be able to pass instances of matplotlib's axes class to plotting methods so that you could tell it to generate the plot in a given figure/subfigure.

The difficulty with all of these approaches is how to make them conveniently handle plotting methods that generate multiple plots. That's especially annoying because the user would have to figure out ahead of time how many plots the methods are going to generate, then prepare the required number of subfigures, then pass them all in the correct order to the plotting method. Admittedly that's not impossible, but it is tedious and error prone.

**Comment by charmasaur** [comment]
Yeah, I've struggled with this question too. One idea I've had is for the user to pass in an "axes factory", which would be a callable that creates a suitable number of `Axes` instance. That moves the responsibility for counting the plots into the function, which has a better chance of getting it right than the user. For example, a user who wants separate figures for each plot could use `lambda n: [plt.figure().axes[0] for _ in range(n)]`, a user who wants to pack them all into a single figure could use `lambda n: plt.subplots(n)[1]`, and so on. I've never actually implemented it to see how it works in practice though -- I'm sure it has its problems too.

**Comment by zakv** [comment]
That's an interesting idea, certainly better than anything I've thought of.

**Comment by sebbleroni** [comment]
> ```python
> desired_fig_number = 34  # Some random figure number.
> ```

T

> Yeah for a while I considered issuing a PR to add more control over where the plots are generated, but I couldn't decide on a simple, flexible, and backwards compatible way to do it nicely.
> 
> A quick/hacky way to do something similar to what you've mentioned is to manually change the value of `figure_counter` before calling the plotting method:
> 
> ```python
> # Required imports.
> import matplotlib.pyplot as plt
> import mloop.visualizations as mlv
> 
> # Settings.
> controller_archive = r'some_controller_archive.txt'  # Controller archive file name and path.
> desired_fig_number = 34  # Some random figure number.
> 
> # Make the plot on the desired figure.
> controller_visualizer = mlv.ControllerVisualizer(controller_archive)
> plt.figure(desired_fig_number)
> figure_counter_bak = mlv.figure_counter  # Backup figure counter to restore its value later.
> mlv.figure_counter = desired_fig_number - 1
> controller_visualizer.plot_cost_vs_run()
> mlv.figure_counter = figure_counter_bak
> ```
> 
> I don't think this hack let's you make good use of `plt.sca()` so it's not quite as good as your suggestion in that way. Ideally you'd be able to pass instances of matplotlib's axes class to plotting methods so that you could tell it to generate the plot in a given figure/subfigure.
> 
> The difficulty with all of these approaches is how to make them conveniently handle plotting methods that generate multiple plots. That's especially annoying because the user would have to figure out ahead of time how many plots the methods are going to generate, then prepare the required number of subfigures, then pass them all in the correct order to the plotting method. Admittedly that's not impossible, but it is tedious and error prone.

Thanks a lot for that idea, perfectly fine a dirty fix for my current situation ;)

**Comment by sebbleroni** [comment]
> Yeah for a while I considered issuing a PR to add more control over where the plots are generated, but I couldn't decide on a simple, flexible, and backwards compatible way to do it nicely.
> 
> A quick/hacky way to do something similar to what you've mentioned is to manually change the value of `figure_counter` before calling the plotting method:
> 
> ```python
> # Required imports.
> import matplotlib.pyplot as plt
> import mloop.visualizations as mlv
> 
> # Settings.
> controller_archive = r'some_controller_archive.txt'  # Controller archive file name and path.
> desired_fig_number = 34  # Some random figure number.
> 
> # Make the plot on the desired figure.
> controller_visualizer = mlv.ControllerVisualizer(controller_archive)
> plt.figure(desired_fig_number)
> figure_counter_bak = mlv.figure_counter  # Backup figure counter to restore its value later.
> mlv.figure_counter = desired_fig_number - 1
> controller_visualizer.plot_cost_vs_run()
> mlv.figure_counter = figure_counter_bak
> ```
> 
> I don't think this hack let's you make good use of `plt.sca()` so it's not quite as good as your suggestion in that way. Ideally you'd be able to pass instances of matplotlib's axes class to plotting methods so that you could tell it to generate the plot in a given figure/subfigure.
> 
> The difficulty with all of these approaches is how to make them conveniently handle plotting methods that generate multiple plots. That's especially annoying because the user would have to figure out ahead of time how many plots the methods are going to generate, then prepare the required number of subfigures, then pass them all in the correct order to the plotting method. Admittedly that's not impossible, but it is tedious and error prone.

Thanks a lot, that works perfectly fine for my case!
