### ISSUE TITLE
Record global minima throughout learner process

### ISSUE THREAD

**Issue by JKalnins** [michaelhush/M-LOOP#81]
I'm trying to study the evolution of the GP learner over time (i.e. how does the fit improve after 10, 50, 100... runs). My original method involved collecting the parameters from the controller_archive dictionary for each run where a lower cost was found than all previous runs:

![cost-vs-run-github-issue](https://user-images.githubusercontent.com/59579351/99992206-efc21c00-2dad-11eb-92bd-dca8473aae01.png)

(plotting cost of each run vs run number, blue points are runs, blue line marks current minimum cost and red markers represent some examples of new, better costs being found)

However this method starts to work less well when noise is added to the fit, as the cost function can't decrease as quickly, and I think it would be interesting to see how the learner's best guess changes over time.

The ideal solution for this would be to optionally run mloop.learners.find_global_minima() and record the output every x runs in the learner_archive or controller_archive. Optionally because it will probably cost performance even though it's only a quick search, if it runs often.

Currently, find_global_minima() is only run if the Learner attribute predict_global_minima_at_end is True, after optimisation. This change would mean the loop within Learner.run() is modified to include an if statement:

```python
self.best_params_every_x_runs = []
for _ in range(self.generation_num):
    self.log.debug('Gaussian process learner generating parameter:'+ str(self.params_count+1))
    next_params = self.find_next_parameters()
    self.params_out_queue.put(next_params)
    if record_minima_over_time:
        if _ % x == 0:
            self.best_params_every_x_runs.append(self.find_global_minima())
    if self.end_event.is_set():
        raise LearnerInterrupt()
```

Here, `x` is the repetition rate aka how often the global minimum is checked and record_minima_over_time is a boolean which is True if recording is enabled. This is from the GaussianProcessLearner but I assume the NeuralNetLearner would work similarly.

I'd be happy to implement this in principle but I haven't fully understood how the controller_archive process works yet, and I'm very new to open-source & github. I checked the current parameters in both controller & learner archive and they don't appear to contain this data already either. If there's a way to do this without a pull request, please let me know!

**Comment by zakv** [comment]
Hi JKalnins,

>  If there's a way to do this without a pull request, please let me know!

Yep! I would recommend installing M-LOOP in a way that allows you to play around with its code directly. To do that:

1. Fork M-LOOP on github
2. Clone your fork to your computer
3. Install your cloned copy of M-LOOP as an editable pip install
    * To perform an editable install, use pip's `-e` flag, e.g. `pip install -e path/to/M-LOOP`
    * You may want to do this in a virtual environment
4. Edit the code to your heart's content!
    * Any changes you make to the code will take effect when you restart your python interpreter.

>  I haven't fully understood how the controller_archive process works yet

I'm getting the impression that at the moment you want to try some things out and learn about how M-LOOP performs. My recommendation would then be to do things in a quick/easy/hacky way for now. After that, if you think the edits you've made would be helpful to the general user then you can implement them more properly by logging to the archives and issue a PR to share your changes! Along those lines, it might just be easier for now to log the results you're interested in to some other file, e.g.

```python
with open('/path/to/some_file.txt', 'a') as my_log:
    my_log.write("Parameter value: " + str(parameter) + "\n")
```

If you do decide that you'd like to include this data in the archives though, I'd be happy to give further guidance along those lines.

>  I think it would be interesting to see how the learner's best guess changes over time.

It might be helpful to know that `GaussianLearner.find_next_parameters()` (which is called each iteration that uses the learner) is nearly identical to `GaussianLearner.find_global_minima()`. The main difference is that `find_next_parameters()` cycles through the values in `self.bias_func_uncer_factor` to pick values where it has larger uncertainty. However, once each generation the uncertainty bias is set to 0, which makes `GaussianLearner.find_next_parameters()` do the same things as `GaussianLearner.find_global_minima()`. If you'd like you can just log that value by adding something like this to `GaussianLearner.find_next_parameters()` right before its `return` statement:

```python
        if self.uncer_bias == 0:
            with open('/path/to/some_file.txt', 'a') as my_log:
                my_log.write("Predicted best params: " + str(next_params) + "\n")
                my_log.write("Predicted cost: " + str(next_cost) + "\n")
```

That would also have the advantage that it is run only once every generation, i.e. only once for each time the gaussian process is fit.

**Comment by JKalnins** [comment]
Amazing, I'll have a look through this, thanks for your help!
