### ISSUE TITLE
Issue while loading my_config.txt 

### ISSUE THREAD

**Issue by stanlee321** [michaelhush/M-LOOP#9]
While I run the comand M-LOOP -c [my_config.txt] in the root where the comand "M-LOOP" is invoked, appear me two errors, I solved the fist one but later appear the secod error :

1rs error:

root@10814d9fcf9e:/notebooks/M-LOOP# M-LOOP -c [my_config.txt]                                                             Traceback (most recent call last):                                                                                        File "/usr/local/bin/M-LOOP", line 6, in <module>                                                                         exec(compile(open(__file__).read(), __file__, 'exec'))                                                                File "/notebooks/M-LOOP/bin/M-LOOP", line 38                                                                              main(sys.argv[1:])  
IndentationError: unindent does not match any outer indentation level

solve this by modifieding the line of code 37 in /bin/M-LOOP file : 

```
if __name__=="__main__":
	mp.freeze_support()
	main(sys.argv[1:])
```
and then  run : M-LOOP -c [my_config.txt]

2nd Error:

Traceback (most recent call last):
  File "/usr/local/bin/M-LOOP", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/notebooks/M-LOOP/bin/M-LOOP", line 38, in <module>
    main(sys.argv[1:])
  File "/notebooks/M-LOOP/bin/M-LOOP", line 34, in main
    _ = mll.launch_from_file(config_filename)
  File "/notebooks/M-LOOP/mloop/launchers.py", line 26, in launch_from_file
    file_kwargs = mlu.get_dict_from_file(config_filename,'txt')
  File "/notebooks/M-LOOP/mloop/utilities.py", line 159, in get_dict_from_file
    dictionary = txt_file_to_dict(filename)
  File "/notebooks/M-LOOP/mloop/utilities.py", line 113, in txt_file_to_dict
    with open(filename,'r') as in_file:
FileNotFoundError: [Errno 2] No such file or directory: '[my_config.txt]'

I confused about this :/ , the file is in the root where the M-LOOP is called.

**Comment by michaelhush** [comment]
I'll look into fixing the first problem today. What operating system are you using?

With regard to the second issue, you are supposed to drop the square brackets and just put the file name. The command should be

M-LOOP -c my_config.txt

Let me know if that works. Sorry about the confusion, I'll update the documentation to make this clearer.

**Comment by michaelhush** [comment]
I fixed the indentation error in the M-LOOP file. If you update your installation and install it again with

git pull origin master
python setup.py develop

I will add another test to catch this issue in the next update. I'm going to close this issue as I think removing the brackets should fix your second issue. Let me know if there are any other issues.

**Comment by stanlee321** [comment]
Cool! now works perfectly!. The issue number 2 comes from the use of the square brakets. Thanks for everything. Regards.
